---
title: "FinalProject"
author: "Stephanie K Moore"
date: "5/5/2016"
output: html_document
---

```{r, label = "SETUP", message = FALSE, warning = FALSE}
library(ggplot2)
library(msm)
library(DT)

t <- 10
trialmaxrating <- numeric(t)
trialmaxskills <- numeric(t) 
trialmaxcombo <- numeric(t)
trialmeanrating <- numeric(t)
trialmeanskills <- numeric(t)
trialmeancombo <- numeric(t)

g <- numeric(10)  

p <- 8     # p = num people interviewed
cand <- matrix(nrow=8,ncol=13)

q <- 10    # q = num qualities sought
qual <- c("Fr","Ger","acct","IQ","start","tact","type","punc","loyal","humor")

skills <- numeric()  # skill lvl of ea quality 1-10 (ten high)

for (k in 1:t) { # for t trials 
  for (i in 1:p) { # with 8 candidates each
    skills <- sample(1:10,10,replace=TRUE)
    cand[i,1] <- mean(skills) # candidate rating is means of her skills
    cand[i,2] <- sum(skills >= 5) # num skills gt or eq to 5?
    if (cand[i,1] >= 5.00 && cand[i,2] >= 5.00) {
      cand[i,3] <- mean(skills) + sum(skills >= 5)}
    else {
      cand[i,3] <- "NA"} 
    for (j in 1:q) { # check on 10 skills
      if (skills[j] >= 5) {
        cand[i,j+3] <- qual[j]}
      else {
        cand[i,j+3] <- "NA"}
    }
  }
  trialmaxrating[k] <- max(cand[i,1]) # record max rating for this trial
  trialmeanrating[k] <- mean(as.numeric(cand[i,1])) # mean rating for this trial
  trialmaxskills[k] <- max(cand[i,2]) # record max skills this trial
  trialmeanskills[k] <- mean(as.numeric(cand[i,2])) # mean skills this trial
  trialmaxcombo[k] <- max(cand[i,3], na.rm = TRUE) # max combo rate + skills this trial
  trialmeancombo[k] <- mean(as.numeric(cand[i,3]), na.rm = TRUE) # mean combo this trial
  g[k] <- DT::datatable(cand, rownames = c("1st","2nd","3rd","4th",
                                 "5th","6th","7th","8th"),
              colnames = c("   Rating","#Skills","","", "", "", "",
              "","","","",""))
} 
g
```

```{r, label = "CALC", message = FALSE, warning = FALSE}

mean(as.numeric(trialmaxrating)) # mean max rating over all trials
max(trialmaxrating) # max rating over all trials

mean(as.numeric(trialmaxskills)) # mean of max skills all trials
max(trialmaxskills) # max skills over all trials

mean(as.numeric(trialmaxcombo), na.rm = TRUE) # mean of max skills all trials
max(as.numeric(trialmaxcombo), na.rm = TRUE) # max skills over all trials

x <- c(1,2,3,4,5,6,7,8,9,10)
mnx <- mean(x)
sum(x)
sdx <-sd(x)

tnd <- dtnorm(1:10,mnx,sdx,1,10)
tnd
tnddf <- as.data.frame(tnd)
# These are expected values not actual trial values
DT::datatable(tnddf, rownames = c("%Rated 1","%Rated 2","%Rated 3",
                                  "%Rated 4","%Rated 5","%Rated 6",
                                  "%Rated 7","%Rated 8","%Rated 9",
                                  "%Rated 10"), colnames = "Truncated Normal Distribution Probabilities")   

tnp <- ptnorm(1:10,mnx,sdx,1,10) 
tnp

plot(1:10,tnp)
plot(1:10,tnd)

rdf <- as.data.frame(trialmeanrating)

gtmr <- ggplot(data=rdf, aes(x=rdf$trialmeanrating,fill="blue")) + 
  geom_histogram(binwidth=1, colour = "blue", alpha = 0.3, position="dodge") +
  labs(x = "Mean Rating", y="Count", title = "Mean Rating by Trial") +
  scale_x_continuous(breaks=1:10) +
  scale_y_continuous(breaks = seq(0, 700, by = 50)) +
  theme_bw() +
  guides(fill=FALSE)
gtmr

sdf <- as.data.frame(trialmeanskills)

gtms <- ggplot(data=sdf, aes(x=sdf$trialmeanskills,fill="blue")) + 
  geom_histogram(binwidth=1, colour = "black", alpha = 0.3, position="dodge", na.rm = TRUE) +
  labs(x = "Mean # Skills", y="Count", title = "Mean Number Skills by Trial") +
  scale_x_continuous(breaks=1:10) +
  scale_y_continuous(breaks = seq(0, 700, by = 50)) +
  theme_bw() +
  guides(fill=FALSE)
gtms

cdf <- as.data.frame(trialmeancombo)

gtmc <- ggplot(data=cdf, aes(x=cdf$trialmeancombo,fill="blue")) + 
  geom_histogram(binwidth=1, colour = "green", alpha = 0.3, position="dodge") +
  labs(x = "Candidates with Rating >= 5 with 5 or more Skills >= 5", y="Count", title = "Mean of Rating + Skill Combo by Trial") +
  scale_x_continuous(breaks=1:20) +
  scale_y_continuous(breaks = seq(0, 200, by = 20)) +
  theme_bw() +
  guides(fill=FALSE)
gtmc
```


