---
title: "Shonkwiler HW Description"
author: "Stephanie K Moore"
date: "1/26/2016"
output: html_document
---
1. Perform a large number of trials of Buffon's needle problem and estimate the value of pi.  Plot the error as a function of the number of trials.

4. Suppose a "reward" r(x) is given upon the roll of a pair of dice as follows: r(x) = 1/x, for 2,3, ... , 12.  Estimate the expectation of r by simulation and compare to the theoretical value.

6. Generate a sequence of characters from the alphabet {a,b,c,d} with each new character chosen with equal probability and independently of the previous choices.  Now slide a "window" of length 4 along this sequence and record the words that you get.  How many characters do you expect to have to generate before you see all possible 4^4= 256 different words?  Use a simulation to answer this question.  Run the simulation for alphabet sizes of 5, 6, and 7 with window sizes 4 and 5.

8. Use a biased coin to simulate a random walk of 30 steps on a line.  If the coin falls heads (H), take one step to the right, if it falls tails (T), take one step left.  Use Pr(H)=0.6 and Pr(T)=0.4. 

    a) Plot a sample path
    b) Make a histogram for 200 such random walks
    c) Report the sample mean of the 200 walks
    d) Report the sample variance of the 200 walks
    e) compare the mean and variance to their theoretical values

10. By simulation, estimate the chance of being dealt a "pair" in poker.  Compare to the theoretical value.

13. An early detection test for HIV is 98% accurate.  In a certain community, 3% of the population has HIV.  What is the probability that a random person with a positive test for HIV actually has the disease?  Simulate this by selecting a person at random from the population and deciding whether or not the person has HIV.  Then administer the test and determine whether is was positive.  Keep a counter for the times that the test is positive and the times the test is positive AND the person has HIV.
