---
title: "Group Creek Project - Do You Hear the Banjos?"
author: "Stephanie K Moore"
date: "4/5/2016"
output: pdf_document
---
Measurements were taken 5 days:
Wed 3/30/16 about 6-7 pm
Fri 4/1/16 about 1-2 pm
Sun 4/3/16 about 5-6 pm
Tue 4/5/16 about 5-6 pm


4th spot:  (closer to Depot ST)

```{r}
library(ggplot2)
library(DT)

# Store temperature for each of 5 days in Fahrenheit #
temp <- matrix(data=c(66,45,67,44,55),nrow=5,ncol=1,byrow=FALSE)

# Convert temp to Celsius #
for (c in 1:5) {
  temp[c] <- (5/9)*(temp[c]-32)
}

pipelen <- 48*2.54/100

#mcubedmx holds near, middle and far depths, width, and volume at 4 locations in meters #
mcubedmx <- matrix(data=NA,nrow=4,ncol=5,byrow=TRUE,dimnames=list(c(1:4),c("Near Depth","Mid-Depth","Far Depth","Width","Volume"))) 

mcubedmx[1,] <- c(.1524,.3810,.1778,3.7846,0) 
mcubedmx[2,] <- c(.0889,.1778,.1016,1.6256,0) 
mcubedmx[3,] <- c(.1143,.1651,.0762,2.7432,0) 
mcubedmx[4,] <- c(.2032,.5080,.1397,3.8354,0) 

# Calculate volume of creek at 4 locations #
for (m in 1:4) {
  csect <- .5*mcubedmx[m,4]*(mcubedmx[m,1]+mcubedmx[m,3])+.25*mcubedmx[m,4]*(2*mcubedmx[m,2]-mcubedmx[m,1]-mcubedmx[m,3])
  mcubedmx[m,5] <- csect*pipelen
}

# Define a matrix to hold data for 3 trials each at 4 locations for 5 days #
timemx <- matrix(data=NA,nrow=20,ncol=6,byrow=TRUE,dimnames=list(c(1:20),c("Day","Location","Trial 1","Trial 2","Trial 3","Mean of Trials")))
timemx[1,] <- c(1,1,6.76,6.1,10.56,0)     # bobber only this one time
timemx[2,] <- c(1,2,6.08,6.48,9.61,0)
timemx[3,] <- c(1,3,6.23,6.83,6.08,0)
timemx[4,] <- c(1,4,0,0,0,0)              # no data on 1st day

timemx[5,] <- c(2,1,6.93,5.65,6.11,0)
timemx[6,] <- c(2,2,3.75,4.22,3.24,0)
timemx[7,] <- c(2,3,4.93,5.31,5.88,0)
timemx[8,] <- c(2,4,0,0,0,0)              # no data on 2nd day

timemx[9,] <- c(3,1,7.3,5.83,5.65,0)
timemx[10,] <- c(3,2,2.81,2.51,2.57,0)
timemx[11,] <- c(3,3,3.51,3.67,3.42,0)
timemx[12,] <- c(3,4,0,0,0,0)             # no data on 3rd day

timemx[13,] <- c(4,1,6.42,6.20,5.63,0)
timemx[14,] <- c(4,2,2.58,2.59,2.66,0)
timemx[15,] <- c(4,3,2.77,3.21,3.10,0)
timemx[16,] <- c(4,4,9.03,9.63,8.42,0)

timemx[17,] <- c(5,1,0,0,0,0)
timemx[18,] <- c(5,2,0,0,0,0)
timemx[19,] <- c(5,3,0,0,0,0)
timemx[20,] <- c(5,4,0,0,0,0) 

for (i in 1:16) {
  timemx[i,6] <- mean(timemx[i,3:5])
}
```

```{r}
# Create flow rate matrix to hold 5 days of flow rate data at each of 4 locations #
flowmx <- matrix(data=NA,nrow=5,ncol=4,byrow=TRUE,
                 dimnames=list(c(1:5),c("Loc1","Loc2","Loc3","Loc4")))
i <- 1
for (d in 1:4) { 
  for (p in 1:4) {
    if (timemx[i,6] != 0) {
      flowmx[d,p] <- mcubedmx[p,5]/timemx[i,6]}
    else {
      flowmx[d,p] <- 0}
    i <- i + 1
  }
}
```

```{r}
library(gridExtra)
g1 <- ggplot(data = NULL, aes(y = flowmx[1,], x = mcubedmx[,5])) +
  geom_point(color = "red", size = 2) +
  geom_line(linetype = 1, color = "blue") +
  theme_bw() +
  labs(y = "Flow Rate (in m^3/sec)", x = "Volume m-cubed by Loc", title = "Flow Rates vs. Volume by Location (Metric)") 
plot(g1)
g2 <- ggplot(data = NULL, aes(y = flowmx[2,], x = mcubedmx[,5])) +
  geom_point(color = "green", size = 2) +
  geom_line(linetype = 1, color = "blue") +
  theme_bw() +
  labs(y = "Flow Rate (in m^3/sec)", x = "Volume at 4 Locations", title = "Flow Rates vs. Volume by Location (Metric)") 
plot(g2)
g3 <- ggplot(data = NULL, aes(y = flowmx[3,], x = mcubedmx[,5])) +
  geom_point(color = "orange", size = 2) +
  geom_line(linetype = 1, color = "blue") +
  theme_bw() +
  labs(y = "Flow Rate (in m^3/sec)", x = "Volume at 4 Locations", title = "Flow Rates vs. Volume by Location (Metric)") 
plot(g3)
g4 <- ggplot(data = NULL, aes(y = flowmx[4,], x = mcubedmx[,5])) +
  geom_point(color = "purple", size = 2) +
  geom_line(linetype = 1, color = "blue") +
  theme_bw() +
  labs(y = "Flow Rate (in m^3/sec)", x = "Volume at 4 Locations", title = "Flow Rates vs. Volume by Location (Metric)") 
plot(g4)
grid.arrange(g1,g2,g3,g4,ncol=4)

```
